# configuration for https://travis-ci.org/daloji/blockchain
sudo: false
dist: xenial
language: java
jdk:
  - openjdk8
script:
 - mvn clean install verify -Pjacoco coveralls:report
after_success: "sbt coveralls"
